### ISSUE TITLE
version numbers do not match

### ISSUE THREAD

**Issue by tessus** [ThibaultJanBeyer/joplin-sheets#1]
Please make sure that the version numbers in `package.json` and `manifest.json` match.

Right now the plugin version number is 1.0.0, but it is published to npm as 0.1.1

On another note, does this plugin use a 3rd party server or do you bundle luckysheet with the plugin? In either case this should be mentioned in the README. You can also create a topic in https://discourse.joplinapp.org/c/plugins/18 to promote your plugin. (Your choice of course.)

**Comment by ThibaultJanBeyer** [comment]
Hi Thank you, I was wondering where the version comes from and tried to adapt the package JSON to the manifest one 🤦 
Yes, it bundles lucky sheet into the plugin, I'll mention that. I'm using it privately and will advertise once I'm confident enough about this plugin.

**Comment by tessus** [comment]
Great, thanks for the info! Nice plugin.
